'use server'

import { createClient } from '@/utils/supabase/server'
import { cookies } from 'next/headers'
import { Resend } from 'resend'
import { revalidatePath } from 'next/cache'

const resend = new Resend(process.env.RESEND_API_KEY)

export type InviteState = { error?: string; success?: boolean } | null

export async function sendTenantInvitation(
  prevState: InviteState,
  formData: FormData
): Promise<InviteState> {
  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  const tenantId = formData.get('tenant_id') as string
  const email = formData.get('email') as string

  if (!tenantId || !email) return { error: 'Datos incompletos.' }

  // Create invitation record (token auto-generated by DB default)
  const { data: inv, error: invError } = await supabase
    .from('tenant_invitations')
    .insert({ tenant_id: tenantId, email })
    .select()
    .single()

  if (invError) return { error: invError.message }

  const inviteUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invitacion/${inv.token}`

  // Fetch tenant name for email
  const { data: tenant } = await supabase
    .from('tenants')
    .select('first_name, last_name')
    .eq('id', tenantId)
    .single()

  const tenantName = tenant ? `${tenant.first_name} ${tenant.last_name}` : 'Inquilino'

  const { error: emailError } = await resend.emails.send({
    from: 'RentManager <noreply@rentmanager.app>',
    to: email,
    subject: 'Invitación al Portal de Inquilinos',
    html: `
      <div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:32px 16px">
        <h2 style="color:#1a1a2e;margin-bottom:8px">Hola, ${tenantName}</h2>
        <p style="color:#64748b;margin-bottom:24px">
          Tu propietario te ha invitado a acceder al portal de inquilinos donde podrás
          ver tus pagos, reportar mantenimiento y acceder a tus documentos.
        </p>
        <a href="${inviteUrl}"
          style="display:inline-block;background:#10b981;color:#fff;padding:12px 24px;
                 border-radius:8px;text-decoration:none;font-weight:600">
          Crear mi cuenta
        </a>
        <p style="color:#94a3b8;font-size:12px;margin-top:24px">
          Este enlace expira en 7 días. Si no esperabas este correo, puedes ignorarlo.
        </p>
      </div>
    `,
  })

  if (emailError) return { error: 'Error al enviar el correo. Intenta nuevamente.' }

  revalidatePath('/tenants')
  return { success: true }
}

export async function acceptInvitation(token: string, password: string) {
  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  // Validate token
  const { data: inv, error: invError } = await supabase
    .from('tenant_invitations')
    .select('*, tenant:tenants(first_name, last_name, email)')
    .eq('token', token)
    .single()

  if (invError || !inv) return { error: 'Enlace de invitación inválido.' }
  if (inv.accepted_at) return { error: 'Esta invitación ya fue utilizada.' }
  if (new Date(inv.expires_at) < new Date()) return { error: 'Esta invitación ha expirado.' }

  // Create auth user with tenant role
  const { data: authData, error: signUpError } = await supabase.auth.signUp({
    email: inv.email,
    password,
    options: {
      data: { role: 'tenant' },
    },
  })

  if (signUpError) return { error: signUpError.message }
  if (!authData.user) return { error: 'No se pudo crear la cuenta.' }

  // Link tenant record to auth user
  const { error: updateError } = await supabase
    .from('tenants')
    .update({ user_id: authData.user.id })
    .eq('id', inv.tenant_id)

  if (updateError) return { error: updateError.message }

  // Mark invitation as accepted
  await supabase
    .from('tenant_invitations')
    .update({ accepted_at: new Date().toISOString() })
    .eq('id', inv.id)

  // Sign in the new user
  await supabase.auth.signInWithPassword({ email: inv.email, password })

  return { success: true }
}

export async function getTenantInvitation(tenantId: string) {
  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  const { data } = await supabase
    .from('tenant_invitations')
    .select('*')
    .eq('tenant_id', tenantId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  return data
}
